name: popover_example
description: Popover Example.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: '>=3.16.1'

dependencies:
  flutter:
    sdk: flutter

  popover:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
